version: "2"
services:
  admin:
    image: admin
    container_name: admin
    env_file: .env
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql
    container_name: admin-mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - /tmp/data/admin/mysql:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d